version: "3.7"
services:
  gtest-grafana:
    image: gtest-grafana:7.0.0
    build:
      context: ./dockerfiles
      dockerfile: DockerfileGrafana
    container_name: gtest-grafana
    depends_on:
      - gtest-mongods
    restart: always
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASS}
    volumes:
      - gtest_grafana:/var/lib/grafana
      - gtest_grafana_plugins:/var/lib/grafana/plugins
      - ./dev/log/grafana:/var/log/grafana
    networks:
      gtest:
        aliases:
          - grafana
    ports: [3000:3000]

  gtest-mongods:
    image: gtest-mongods
    build:
      context: ./dockerfiles
      dockerfile: DockerfileMongoDs
    container_name: gtest-mongods
    restart: always
    volumes:
      - gtest_grafana_plugins:/application
    networks:
      gtest:
        aliases:
          - mongods

  gtest-postgres:
    image: gtest-postgres
    build:
      context: ./dockerfiles
      dockerfile: DockerfilePostgres
    container_name: gtest-core-postgres-db
    restart: always
    volumes:
      - gtest_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_PASSWORD: ${PGSQL_PASS}
      POSTGRES_DB: ${PGSQL_DB}
    ports: [5432:5432]
    networks:
      gtest:
        aliases:
          - postgres

  gtest-mongo:
    image: gtest-mongodb
    build:
      context: ./dockerfiles
      dockerfile: DockerfileMongo
    container_name: gtest-mongo
    restart: always
    volumes:
      - gtest_mongo:/data/db
      - ./fixtures:/fixtures
    ports: [27017:27017]
    networks:
      gtest:
        aliases:
          - mongo

  gtest-adminer:
    image: adminer:4.7.7
    container_name: gtest-adminer
    restart: always
    ports: [8080:8080]
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
    networks:
      gtest:
        aliases:
          - adminer

  gtest-mongo-express:
    image: mongo-express:latest
    container_name: gtest-mongo-express
    restart: always
    ports: [8081:8081]
    networks:
      gtest:
        aliases:
          - mongoexpress

networks:
  gtest:

volumes:
  gtest_grafana:
  gtest_grafana_plugins:
  gtest_postgres:
  gtest_mongo:
